#include "stdafx.h"
#include "Editors.h"

namespace oak
    {

    DEFINE_ENUM_ENTRY_BEGIN(EditorType)
    DEFINE_ENUM_ENTRY(EditorType::Selector, "Selector")
    DEFINE_ENUM_ENTRY(EditorType::iOS, "iOS")
    DEFINE_ENUM_ENTRY(EditorType::Android, "Android")
    DEFINE_ENUM_ENTRY(EditorType::Resource, "Resource")
    DEFINE_ENUM_ENTRY(EditorType::Config, "Config")
    DEFINE_ENUM_ENTRY(EditorType::Console, "Console")
    DEFINE_ENUM_ENTRY(EditorType::MainClock, "MainClock")
    DEFINE_ENUM_ENTRY(EditorType::Plugin, "Plugin")
    DEFINE_ENUM_ENTRY(EditorType::Display, "Display")
    DEFINE_ENUM_ENTRY(EditorType::Render, "Render")
    DEFINE_ENUM_ENTRY(EditorType::Mouse, "Mouse")
    DEFINE_ENUM_ENTRY(EditorType::Input, "Input")
    DEFINE_ENUM_ENTRY(EditorType::InputSet, "InputSet")
    DEFINE_ENUM_ENTRY(EditorType::Locale, "Locale")
    DEFINE_ENUM_ENTRY(EditorType::Language, "Language")
    DEFINE_ENUM_ENTRY(EditorType::Physics, "Physics")
    DEFINE_ENUM_ENTRY(EditorType::SoundSystem, "SoundSystem")
    DEFINE_ENUM_ENTRY(EditorType::Screenshot, "Screenshot")
    DEFINE_ENUM_ENTRY(EditorType::Param, "Param")
    DEFINE_ENUM_ENTRY(EditorType::Object, "Object")
    DEFINE_ENUM_ENTRY(EditorType::Graphic, "Graphic")
    DEFINE_ENUM_ENTRY(EditorType::Text, "Text")
    DEFINE_ENUM_ENTRY(EditorType::Font, "Font")
    DEFINE_ENUM_ENTRY(EditorType::Body, "Body")
    DEFINE_ENUM_ENTRY(EditorType::BodyPartSphere, "BodyPartSphere")
    DEFINE_ENUM_ENTRY(EditorType::BodyPartBox, "BodyPartBox")
    DEFINE_ENUM_ENTRY(EditorType::BodyPartMesh, "BodyPartMesh")
    DEFINE_ENUM_ENTRY(EditorType::RevoluteJoint, "RevoluteJoint")
    DEFINE_ENUM_ENTRY(EditorType::PrismaticJoint, "PrismaticJoint")
    DEFINE_ENUM_ENTRY(EditorType::SpringJoint, "SpringJoint")
    DEFINE_ENUM_ENTRY(EditorType::RopeJoint, "RopeJoint")
    DEFINE_ENUM_ENTRY(EditorType::PulleyJoint, "PulleyJoint")
    DEFINE_ENUM_ENTRY(EditorType::SuspensionJoint, "SuspensionJoint")
    DEFINE_ENUM_ENTRY(EditorType::WeldJoint, "WeldJoint")
    DEFINE_ENUM_ENTRY(EditorType::FrictionJoint, "FrictionJoint")
    DEFINE_ENUM_ENTRY(EditorType::GearJoint, "GearJoint")
    DEFINE_ENUM_ENTRY(EditorType::AnimationSet, "AnimationSet")
    DEFINE_ENUM_ENTRY(EditorType::Animation, "Animation")
    DEFINE_ENUM_ENTRY(EditorType::Animation1, "Animation1")
    DEFINE_ENUM_ENTRY(EditorType::Viewport, "Viewport")
    DEFINE_ENUM_ENTRY(EditorType::Camera, "Camera")
    DEFINE_ENUM_ENTRY(EditorType::Clock, "Clock")
    DEFINE_ENUM_ENTRY(EditorType::Sound, "Sound")
    DEFINE_ENUM_ENTRY(EditorType::FX, "FX")
    DEFINE_ENUM_ENTRY(EditorType::FXSlot, "FXSlot")
    DEFINE_ENUM_ENTRY(EditorType::Spawner, "Spawner")
    DEFINE_ENUM_ENTRY(EditorType::Shader, "Shader")
    DEFINE_ENUM_ENTRY(EditorType::TimeLineTrack, "TimeLineTrack")
    DEFINE_ENUM_ENTRY_END()



    }
